version: "3.8"

services:
  db:
    image: postgres:latest

    # used to create the database credentials
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

    ports:
      - "5432:5432"

    volumes:
      - db_data:/data/postgres

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest

    ports:
      - "8079:80"

    environment:
      SRH_MODE: env
      SRH_TOKEN: ct3t-srh-token
      SRH_CONNECTION_STRING: "redis://redis:6379"

    depends_on:
      - redis

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - s3_data:/tmp/localstack/data
    command: >
      sh -c '
        sleep 5;
        aws --endpoint-url=http://localhost:4566 s3 mb s3://ct3t-preview;
        echo "LocalStack ready!"'

volumes:
  db_data:
  s3_data:
